nexus-file-converter:
  debug:
    enabled: false
    suspend: false
  beamline: p48
  template:
    entry/:
      NX_class@: NXentry
      instrument/:
        NX_class@: NXinstrument
        name: p48
  containerEnvVars:
    - name: OTEL_EXPORTER_OTLP_PROTOCOL
      value: "http/protobuf"
    - name: OTEL_EXPORTER_OTLP_ENDPOINT
      value: "http://opentelemetry-collector.tracing:4318/v1/traces"
    - name: OTEL_LOG_LEVEL
      value: debug  

  nodeSelector:
    kubernetes.io/hostname: bl48p-ea-serv-01.diamond.ac.uk
  tolerations:
    - key: nodetype
      operator: Equal
      value: training-rig
      effect: NoSchedule
    - key: beamline
      operator: Equal
      value: bl48p
      effect: NoSchedule

  image:
    tags: "4.1.7-a3"
  volumes:
  - name: nexus-data
    hostPath:
      path: /exports/mybeamline/data/
      type: DirectoryOrCreate

  volumeMounts:
  - name: nexus-data
    mountPath: /exports/mybeamline/data/
    mountPropagation: HostToContainer

  application:
    server:
      port: 8084
    management:
      tracing:
        sampling:
          probability: 1.0
        enabled: true
        
    spring:
      profiles:
        active: rabbitmq
      rabbitmq:
        host: p48-rabbitmq
        username: guest
        password: guest
    files:
      output:
        directory:
          staticDirectory: ""  # explicitly empty, get from StartDocument metadata
        
        devices:
          types:
            det: NX_DETECTOR
            sample_stage: NX_COLLECTION
            sample_stage.x: NX_POSITIONER
            sample_stage.theta: NX_POSITIONER
  securityContext:
    runAsUser: 37888 # p48-detector
    runAsGroup: 37888
