apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tiled-secret
  namespace: p48-beamline
spec:
  encryptedData:
    TILED_SINGLE_USER_API_KEY: AgBto38fr2Xldr3TP+8IwdzCTENPYvlJM+RZ8tYrbn0+mqBz1YTaWCxi+zJapQUYSOt7Fn7zLB12fVbns7TCAIZ0at3rY2wB6ST+kljlISA8lsAah4npImv24/oSzAVqocHSxOpverWqvEM8G3DtU1Wyswlu19Zpj+Nnk07ssy3arRr3GgB7plAH/LW/r7LUkwmJ+XmQyXdDicuic44YrNbhjD0MTBaG4LRMa7scHcqO0ZWYRja+o71WfO0NCle9zeiBTH9WDaOcb9adXEGYKQO3afygBe5gU8Rsfww4+UwaEzqEQeXLquIIIF/4l588xOj19nbAQIg+4XRkxXy6xinkXBckL3NjQzFsrwk9MZ7bT2R2pnfBJVNbbq/f5HJDWP9RDa/HyzxcrZsVmS4sqd2lLF2M7JLtZtPBa6sABCJv7SvQLSh4vmq74YpsTU1wbIVjcqw2Sf/9d1pL7P/S8oWaU2Fxr2oTomHdusYu6YXBRM5UGqOxK1AElRBZW4uS6Wlaq22E4yIX3qzsgd9TujhbDzfCOWFPDsNTb7qm5HkVQhmbzNLF5V8vMqZbGO50ElKpWgCxRYnlafMMiKQr7gI/mIaRLKSHgzL7emBRqSYuk36LC/ExRKDsyK4cGYRorm9rM+7+ZUwsB7/Y9TD1k5n+qZ6+R2kB+9VpNwPratWK5VdKzC3vgv5bas1SnL9jqb8xEz25kXNQYexljCBv8kzdyAzgSEavccjRIyy5VrYFZT1iDIQojcXwa4fVR6eaORIhyRMJRJHfDvdusnbPEMD8
